source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'mysql2'

gem 'omniauth', '~> 1.0.0'
gem 'omniauth-douban'

gem 'settingslogic'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'
  gem 'compass-rails'
  gem 'uglifier', '>= 1.0.3'
  gem 'therubyracer'

  # gem 'sprite-factory', '>= 1.4.0'
  # gem 'chunky_png'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
gem 'devise'
gem "cancan"
gem 'rails_admin', :git => 'https://github.com/halida/rails_admin.git'

gem 'acts-as-taggable-on'
gem 'redcarpet', '1.17.2'
gem 'gravatar-ultimate'
gem 'acts_as_commentable_with_threading', git: "https://github.com/elight/acts_as_commentable_with_threading.git"
gem 'will_paginate', '~> 3.0.pre2'
gem 'simple_form'
gem 'client_side_validations'
# gem 'client_side_validations-simple_form', git: "https://github.com/dockyard/client_side_validations-simple_form.git"

gem 'settingslogic'
gem "auto_strip_attributes", "~> 2.0" 
gem 'rails_autolink'
gem "truncate_html", "~> 0.5.4"

gem 'jquery-rails'
gem 'haml'
gem "haml-rails"
gem "actionmailer_inline_css"
gem 'country_select'
gem 'jcrop-rails'
gem 'chosen-rails'
gem "twitter-bootstrap-rails"
gem "pjax_rails"

group :development, :test do
  gem 'quiet_assets', git: 'https://github.com/AgilionApps/quiet_assets.git', tag: 'v0.1.0'
  gem 'rspec'
  gem 'rspec-rails', "~> 2.6"

  gem "capybara"
  gem 'factory_girl_rails'
  gem 'database_cleaner', "~> 0.7.1"
end
